### ISSUE TITLE
[Bug] Weird jumps on grid container with gaps

### ISSUE THREAD

**Issue by felixmosh** [catamphetamine/virtual-scroller#15] opened 2020-12-11 14:17 UTC
Hi,

I've updated to the latest version (1.6.x), and I've noticed that there are some jumps of the container when the scroller stops.

I'm able to reproduce it on [the demo](https://catamphetamine.gitlab.io/virtual-scroller/).
![ezgif-3-e8c0602e0742](https://user-images.githubusercontent.com/9304194/101913800-28def680-3bcc-11eb-94d1-69842b7677dc.gif)

All you need to do is to add css to the `#messages`
```css
#messages {
    border-top: 2px solid rgb(230, 236, 240);
    display: grid; // <----
    grid-gap: 2em; // <----
}
```

It is not reproduces on `v1.5.x`.

**Comment by catamphetamine** [comment] 2020-12-12 07:15
Fixed in `virtual-scroller@1.6.4`

**Closed as completed by catamphetamine** 2020-12-12 07:15 UTC

**Comment by felixmosh** [comment] 2020-12-12 09:40
The example page is uses the latest version? if so, I still able to recreate the bug

**Comment by catamphetamine** [comment] 2020-12-12 22:24
The example page works for me when using the `#messages` style you've posted.

**Comment by felixmosh** [comment] 2020-12-13 07:34
I'm still able to constantly reproduce the issue 
![Screen Recording 2020-12-13 at 9 31 38](https://user-images.githubusercontent.com/9304194/102006036-4b852280-3d26-11eb-901c-ef00cefd7515.gif)

**Comment by catamphetamine** [comment] 2020-12-13 07:35
I don't see any issues.

You can provide an online demo if you want, along with clear reproduction instructions.

**Comment by felixmosh** [comment] 2020-12-13 07:44
You are correct, looks like there is a difference between changing the styles in dev-tools & starting the app with the styles.


Thank you 🙏🏼
